parameters:
    database_driver:   pdo_pgsql
    database_host:     ec2-54-225-101-202.compute-1.amazonaws.com
    database_port:     5432
    database_name:     d2oqihoi6snr5r
    database_user:     dpjysxcomdagth
    database_password: 90KhGVdRmMQ9Y7ysjXgCX8SbGV

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            de
    secret:            ThisTokenIsNotSoSecretChangeIt

